### ISSUE TITLE
Strange error on first vagrant up [Mac OS 10.8/10.9]

### ISSUE THREAD

**Issue by ryanpcmcquen** [cogitatio/vagrant-hostsupdater#28]
I have received the same error on 2 separate machines (Macbook Pro @ 10.8 /iMac @ 10.9):

```
~/.vagrant.d/gems/gems/vagrant-hostsupdater-0.0.11/lib/vagrant-hostsupdater/HostsUpdater.rb:107:in `digest': can't convert nil into String (TypeError)
  from ~/.vagrant.d/gems/gems/vagrant-hostsupdater-0.0.11/lib/vagrant-hostsupdater/HostsUpdater.rb:107:in `hexdigest'
  from ~/.vagrant.d/gems/gems/vagrant-hostsupdater-0.0.11/lib/vagrant-hostsupdater/HostsUpdater.rb:107:in `signature'
  from ~/.vagrant.d/gems/gems/vagrant-hostsupdater-0.0.11/lib/vagrant-hostsupdater/HostsUpdater.rb:70:in `block in getHostEntries'
  from ~/.vagrant.d/gems/gems/vagrant-hostsupdater-0.0.11/lib/vagrant-hostsupdater/HostsUpdater.rb:69:in `each'
  from ~/.vagrant.d/gems/gems/vagrant-hostsupdater-0.0.11/lib/vagrant-hostsupdater/HostsUpdater.rb:69:in `getHostEntries'
  from ~/.vagrant.d/gems/gems/vagrant-hostsupdater-0.0.11/lib/vagrant-hostsupdater/HostsUpdater.rb:33:in `block in addHostEntries'
  from ~/.vagrant.d/gems/gems/vagrant-hostsupdater-0.0.11/lib/vagrant-hostsupdater/HostsUpdater.rb:32:in `each'
  from ~/.vagrant.d/gems/gems/vagrant-hostsupdater-0.0.11/lib/vagrant-hostsupdater/HostsUpdater.rb:32:in `addHostEntries'
  from ~/.vagrant.d/gems/gems/vagrant-hostsupdater-0.0.11/lib/vagrant-hostsupdater/Action/UpdateHosts.rb:18:in `call'
  from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
  from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/call.rb:57:in `call'
  from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
  from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
  from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
  from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
  from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
  from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/call.rb:57:in `call'
  from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
  from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
  from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
  from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builtin/call.rb:57:in `call'
  from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
  from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
  from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/warden.rb:34:in `call'
  from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/builder.rb:116:in `call'
  from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `block in run'
  from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/util/busy.rb:19:in `busy'
  from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/action/runner.rb:61:in `run'
  from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/machine.rb:147:in `action'
  from /Applications/Vagrant/embedded/gems/gems/vagrant-1.3.5/lib/vagrant/batch_action.rb:63:in `block (2 levels) in run'
```

This is my Vagrantfile:
https://raw.github.com/milojennings/zippy/0.1/Vagrantfile

Everything works perfectly on the second vagrant up.

**Comment by opepin** [comment]
got the same issue on 1.4.3 - vagrant-hostsupdater (0.0.11)

```
[es] Checking for host entries
[es] Forcing shutdown of VM...
[es] Destroying VM and associated drives...
[es] Running cleanup tasks for 'chef_solo' provisioner...
vagrant-hostsupdater-0.0.11/lib/vagrant-hostsupdater/HostsUpdater.rb:107:in `digest': no implicit conversion of nil into String (TypeError)
	from vagrant-hostsupdater-0.0.11/lib/vagrant-hostsupdater/HostsUpdater.rb:107:in `hexdigest'
	from vagrant-hostsupdater-0.0.11/lib/vagrant-hostsupdater/HostsUpdater.rb:107:in `signature'
	from vagrant-hostsupdater-0.0.11/lib/vagrant-hostsupdater/HostsUpdater.rb:70:in `block in getHostEntries'
	from vagrant-hostsupdater-0.0.11/lib/vagrant-hostsupdater/HostsUpdater.rb:69:in `each'
	from vagrant-hostsupdater-0.0.11/lib/vagrant-hostsupdater/HostsUpdater.rb:69:in `getHostEntries'
	from vagrant-hostsupdater-0.0.11/lib/vagrant-hostsupdater/HostsUpdater.rb:33:in `block in addHostEntries'
	from vagrant-hostsupdater-0.0.11/lib/vagrant-hostsupdater/HostsUpdater.rb:32:in `each'
	from vagrant-hostsupdater-0.0.11/lib/vagrant-hostsupdater/HostsUpdater.rb:32:in `addHostEntries'
	from vagrant-hostsupdater-0.0.11/lib/vagrant-hostsupdater/Action/UpdateHosts.rb:18:in `call'
	from /Applications/Vagrant/embedded/gems/gems/vagrant-1.4.3/lib/vagrant/action/warden.rb:34:in `call'
```
Works the second time (and asked for the sudo password to edit the /etc/hosts file)

**Comment by aistis-** [comment]
`vagrant halt && vagrant up` solved the error for me.

**Comment by cgsmith** [comment]
I am not seeing this issue occurring.  Is there a simpler Vagrantfile to use to replicate? Does it only happen on new boxes?

**Comment by ryanpcmcquen** [comment]
@cgsmith you can try this one: https://gist.github.com/ryanpcmcquen/e2f1e9424671c2bbd251

I haven't tried any of these projects in over a year, so the issue may have been fixed by something else at this point.

**Comment by ryanpcmcquen** [comment]
And yes it only happens on new boxes, as @wheelsandcogs said.

**Comment by dtbaker** [comment]
Ditto getting the same error here. Fresh install, just install vagrant 1.7.4 from https://www.vagrantup.com/downloads.html and ran `vagrant plugin install vagrant-hostsupdater` then `vagrant plugin install vagrant-triggers` then `vagrant up` and received:

````
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Removing hosts
==> default: No machine id, nothing removed from /etc/hosts
==> default: Checking for host entries
/home/dtbaker/.vagrant.d/gems/gems/vagrant-hostsupdater-1.0.0/lib/vagrant-hostsupdater/HostsUpdater.rb:110:in `digest': no implicit conversion of nil into String (TypeError)
	from /home/dtbaker/.vagrant.d/gems/gems/vagrant-hostsupdater-1.0.0/lib/vagrant-hostsupdater/HostsUpdater.rb:110:in `hexdigest'
	from /home/dtbaker/.vagrant.d/gems/gems/vagrant-hostsupdater-1.0.0/lib/vagrant-hostsupdater/HostsUpdater.rb:110:in `signature'
	from /home/dtbaker/.vagrant.d/gems/gems/vagrant-hostsupdater-1.0.0/lib/vagrant-hostsupdater/HostsUpdater.rb:73:in `block in getHostEntries'
	from /home/dtbaker/.vagrant.d/gems/gems/vagrant-hostsupdater-1.0.0/lib/vagrant-hostsupdater/HostsUpdater.rb:72:in `each'
	from /home/dtbaker/.vagrant.d/gems/gems/vagrant-hostsupdater-1.0.0/lib/vagrant-hostsupdater/HostsUpdater.rb:72:in `getHostEntries'
	from /home/dtbaker/.vagrant.d/gems/gems/vagrant-hostsupdater-1.0.0/lib/vagrant-hostsupdater/HostsUpdater.rb:36:in `block in addHostEntries'
	from /home/dtbaker/.vagrant.d/gems/gems/vagrant-hostsupdater-1.0.0/lib/vagrant-hostsupdater/HostsUpdater.rb:35:in `each'
	from /home/dtbaker/.vagrant.d/gems/gems/vagrant-hostsupdater-1.0.0/lib/vagrant-hostsupdater/HostsUpdater.rb:35:in `addHostEntries'
	from /home/dtbaker/.vagrant.d/gems/gems/vagrant-hostsupdater-1.0.0/lib/vagrant-hostsupdater/Action/UpdateHosts.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /home/dtbaker/.vagrant.d/gems/gems/vagrant-hostsupdater-1.0.0/lib/vagrant-hostsupdater/Action/RemoveHosts.rb:23:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /home/dtbaker/.vagrant.d/gems/gems/vagrant-triggers-0.5.2/lib/vagrant-triggers/action/trigger.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /home/dtbaker/.vagrant.d/gems/gems/vagrant-triggers-0.5.2/lib/vagrant-triggers/action/trigger.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /home/dtbaker/.vagrant.d/gems/gems/vagrant-triggers-0.5.2/lib/vagrant-triggers/action/trigger.rb:17:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

````

**Comment by cgsmith** [comment]
I'll try and find what is going on - I am seeing the issue as well.

**Comment by cgsmith** [comment]
@dtbaker can you verify that this fixes the issue? You can install this bugfix plugin by downloading, unzipping, and typing `vagrant plugin install vagrant-hostsupdater-1.0.1.gem`

http://d.pr/f/15zfg

**Comment by cgsmith** [comment]
I think the issue was caused by the box not being fully loaded in Vagrant.  Perhaps not all the variables were set? Vagrant SetHostname should be the proper hook for `vagrant up`

**Comment by nzhuk98** [comment]
Just had this same issue. 1.0.1 you linked fixed it.

**Comment by YHuard** [comment]
Thank you @cgsmith, it worked for me as well!

**Comment by federicoweber** [comment]
thanks @cgsmith, that solved it.

**Comment by wannesderoy** [comment]
I too can confirm @cgsmith's fix worked for me. Thanks!

**Comment by cgsmith** [comment]
Fixed in 1.0.1

**Comment by ar000n** [comment]
seems its because of environment variable issue.

**Comment by ryanpcmcquen** [comment]
@ar000n the issue has been fixed since November 2015, why are you commenting on it?

**Comment by Bilge** [comment]
Because it still happens in 1.1.1.

**Comment by jstnbr** [comment]
This issue is still happening for me, and the link above is broken. It's happening because I'm using the alias array feature. I remember a while ago this feature (listed in the Readme) did not work, and still does not work today.

**Comment by kamil-p** [comment]
I had similar issue with vagrant `2.2.14` I downgraded it to `2.2.9` and it worked.

**Comment by sebastienrussellwr** [comment]
I have the same problem here with `2.2.14`

**Comment by corbinjurgens** [comment]
Just updated to 2.2.14, and I also have this error even after updating plugins

```
Traceback (most recent call last):
        26: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
        25: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `action'
        24: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `call'
        23: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/environment.rb:613:in `lock'
        22: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:215:in `block in action'
        21: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:246:in `action_raw'
        20: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
        19: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
        18: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
        17: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'
        16: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
        15: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
        14: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
        13: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/call.rb:43:in `call'
        12: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
        11: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
        10: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
         9: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'
         8: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
         7: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/created.rb:15:in `call'
         6: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
         5: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/commands/up/middleware/store_box_metadata.rb:33:in `call'
         4: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
         3: from C:/Users/corbi/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.2.0/lib/vagrant-hostsupdater/Action/UpdateHosts.rb:17:in `call'
         2: from C:/Users/corbi/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.2.0/lib/vagrant-hostsupdater/HostsUpdater.rb:99:in `addHostEntries'
         1: from C:/Users/corbi/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.2.0/lib/vagrant-hostsupdater/HostsUpdater.rb:152:in `addToHosts'
C:/Users/corbi/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.2.0/lib/vagrant-hostsupdater/HostsUpdater.rb:152:in `+': no implicit conversion of nil into String (TypeError)
```

**Comment by cgsmith** [comment]
@corbinjurgens can you try to uninstall the plugin and then install it again?

**Comment by andrew-pause** [comment]
I am having this seem issue with 2.2.14 on windows. uninstalling the plugin and reinstalling did not resolve the issue

**Comment by asanCar** [comment]
@cgsmith reinstalling vagrant-hostsupdater solved the problem in my Ubuntu Linux.

In my case, I was facing the problem with those versions:
**Vagrant:** 2.2.14
**vagrant-hostsupdater plugin:** 1.1.1.160

Started to work with:
**Vagrant:** 2.2.14
**vagrant-hostsupdater plugin:** 1.2.0

**Comment by skalinkin** [comment]
Just got the same error. 

Bringing machine 'vgpm' up with 'virtualbox' provider...
==> vgpm: [vagrant-hostsupdater] Checking for host entries
==> vgpm: [vagrant-hostsupdater] Writing the following entries to (C:/WINDOWS/system32/drivers/etc/hosts)
==> vgpm: [vagrant-hostsupdater]   192.168.99.25  axs.local, keycloak  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (vgpm) / 
Traceback (most recent call last):
        26: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
        25: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `action'
        24: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `call'
        23: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/environment.rb:613:in `lock'
        22: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:215:in `block in action'
        21: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:246:in `action_raw'
        20: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
        19: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
        18: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
        17: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'
        16: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
        15: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
        14: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
        13: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/call.rb:43:in `call'
        12: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
        11: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
        10: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
         9: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'
         8: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
         7: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/created.rb:15:in `call'
         6: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
         5: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/commands/up/middleware/store_box_metadata.rb:33:in `call'
         4: from C:/HashiCorp/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
         3: from C:/Work/GIT/axs-vgpm/vagrant/.vagrant/plugins/gems/2.6.6/gems/vagrant-hostsupdater-1.2.0/lib/vagrant-hostsupdater/Action/UpdateHosts.rb:17:in `call'
         2: from C:/Work/GIT/axs-vgpm/vagrant/.vagrant/plugins/gems/2.6.6/gems/vagrant-hostsupdater-1.2.0/lib/vagrant-hostsupdater/HostsUpdater.rb:99:in `addHostEntries'
         1: from C:/Work/GIT/axs-vgpm/vagrant/.vagrant/plugins/gems/2.6.6/gems/vagrant-hostsupdater-1.2.0/lib/vagrant-hostsupdater/HostsUpdater.rb:152:in `addToHosts'
C:/Work/GIT/axs-vgpm/vagrant/.vagrant/plugins/gems/2.6.6/gems/vagrant-hostsupdater-1.2.0/lib/vagrant-hostsupdater/HostsUpdater.rb:152:in `+': no implicit conversion of nil into String (TypeError)

**Comment by cgsmith** [comment]
@skalinkin This issue was raised to address. https://github.com/agiledivider/vagrant-hostsupdater/issues/190

If you want to help test if the gem works before releasing it you can do so here: https://github.com/agiledivider/vagrant-hostsupdater/releases/tag/1.2.1-beta

**Comment by skalinkin** [comment]
Will do,
there are a couple more issues.
1. Windows hosts file format does not support commas. So plugin shouldn't
do 1.2.3.4 alias1, alias2, alias3 it should do
1.2.3.4 alias1
1.2.3.4 alias2
1.2.3.4 alias3
for windows.

it is not confirmed but on vagrant destroy, the plugin leaves extra
newline. So after 10 rebuilds I have 10 empty lines before vagrant section.

thanks.

**Comment by ryanpcmcquen** [comment]
Wow, this bug won't die.

**Comment by skalinkin** [comment]
Issue.
Multiple Checks for enty.
usign  1.2.1 BETA
<https://github.com/agiledivider/vagrant-hostsupdater/releases/tag/1.2.1-beta>


VAGRANT FILE
# -*- mode: ruby -*-
# vi: set ft=ruby :
GROUP_NAME = "/VGPM"
IMAGE_NAME = "geerlingguy/centos8"

Vagrant.configure("2") do |config|
  config.vagrant.plugins = "vagrant-hostsupdater"

  config.vm.box = IMAGE_NAME
  config.vm.network "private_network", ip: "192.168.99.25"
  config.vm.synced_folder "../", "/home/vagrant", type: "rsync",
rsync__exclude: ".git/"
  config.vm.provider :virtualbox do |v|
   v.customize ["modifyvm", :id, "--groups", GROUP_NAME]
  end
  config.vm.define "vgpm" do |vgpm|
    vgpm.vm.hostname = "vgpm.local"
    config.hostsupdater.aliases = ["axs.local, keycloak"]
    vgpm.vm.provision :shell, path: "provision.sh"
    vgpm.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 4096]
      v.customize ["modifyvm", :id, "--name", "vgpm"]
    end
  end
end
LOG
Bringing machine 'vgpm' up with 'virtualbox' provider...
==> vgpm: [vagrant-hostsupdater] Checking for host entries
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25 vgpm.local
==> vgpm: [vagrant-hostsupdater] Writing the following entries to
(C:/WINDOWS/system32/drivers/etc/hosts)
==> vgpm: [vagrant-hostsupdater]   192.168.99.25  axs.local, keycloak  #
VAGRANT: d41d8cd98f00b204e9800998ecf8427e (vgpm) /
==> vgpm: [vagrant-hostsupdater] Update Works
==> vgpm: [vagrant-hostsupdater] Checking for host entries
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25 vgpm.local
==> vgpm: [vagrant-hostsupdater] Writing the following entries to
(C:/WINDOWS/system32/drivers/etc/hosts)
==> vgpm: [vagrant-hostsupdater]   192.168.99.25  axs.local, keycloak  #
VAGRANT: d41d8cd98f00b204e9800998ecf8427e (vgpm) /
==> vgpm: [vagrant-hostsupdater] Update Works
==> vgpm: Importing base box 'geerlingguy/centos8'...
==> vgpm: Matching MAC address for NAT networking...
==> vgpm: Checking if box 'geerlingguy/centos8' version '1.0.7' is up to
date...
==> vgpm: [vagrant-hostsupdater] Checking for host entries
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25 vgpm.local
==> vgpm: [vagrant-hostsupdater] Writing the following entries to
(C:/WINDOWS/system32/drivers/etc/hosts)
==> vgpm: [vagrant-hostsupdater]   192.168.99.25  axs.local, keycloak  #
VAGRANT: e822a021a1afdc6c8dde3295110a3a6e (vgpm) /
9a45e779-4469-4348-9602-8273472cfd7f
==> vgpm: [vagrant-hostsupdater] Update Works
==> vgpm: [vagrant-hostsupdater] Checking for host entries
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25 vgpm.local
==> vgpm: [vagrant-hostsupdater] Writing the following entries to
(C:/WINDOWS/system32/drivers/etc/hosts)
==> vgpm: [vagrant-hostsupdater]   192.168.99.25  axs.local, keycloak  #
VAGRANT: e822a021a1afdc6c8dde3295110a3a6e (vgpm) /
9a45e779-4469-4348-9602-8273472cfd7f
==> vgpm: [vagrant-hostsupdater] Update Works
==> vgpm: [vagrant-hostsupdater] Checking for host entries
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25 vgpm.local
==> vgpm: [vagrant-hostsupdater] Writing the following entries to
(C:/WINDOWS/system32/drivers/etc/hosts)
==> vgpm: [vagrant-hostsupdater]   192.168.99.25  axs.local, keycloak  #
VAGRANT: e822a021a1afdc6c8dde3295110a3a6e (vgpm) /
9a45e779-4469-4348-9602-8273472cfd7f
==> vgpm: [vagrant-hostsupdater] Update Works
==> vgpm: Setting the name of the VM: vagrant_vgpm_1607013571429_69746
==> vgpm: Clearing any previously set network interfaces...
==> vgpm: Preparing network interfaces based on configuration...
    vgpm: Adapter 1: nat
    vgpm: Adapter 2: hostonly
==> vgpm: Forwarding ports...
    vgpm: 22 (guest) => 2222 (host) (adapter 1)
==> vgpm: [vagrant-hostsupdater] Checking for host entries
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25 vgpm.local
==> vgpm: [vagrant-hostsupdater] Writing the following entries to
(C:/WINDOWS/system32/drivers/etc/hosts)
==> vgpm: [vagrant-hostsupdater]   192.168.99.25  axs.local, keycloak  #
VAGRANT: e822a021a1afdc6c8dde3295110a3a6e (vgpm) /
9a45e779-4469-4348-9602-8273472cfd7f
==> vgpm: [vagrant-hostsupdater] Update Works
==> vgpm: Running 'pre-boot' VM customizations...
==> vgpm: Booting VM...
==> vgpm: Waiting for machine to boot. This may take a few minutes...
    vgpm: SSH address: 127.0.0.1:2222
    vgpm: SSH username: vagrant
    vgpm: SSH auth method: private key
    vgpm:
    vgpm: Vagrant insecure key detected. Vagrant will automatically replace
    vgpm: this with a newly generated keypair for better security.
    vgpm:
    vgpm: Inserting generated public key within guest...
    vgpm: Removing insecure key from the guest if it's present...
    vgpm: Key inserted! Disconnecting and reconnecting using new SSH key...
==> vgpm: Machine booted and ready!
==> vgpm: [vagrant-hostsupdater] Checking for host entries
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25 vgpm.local
==> vgpm: [vagrant-hostsupdater] Writing the following entries to
(C:/WINDOWS/system32/drivers/etc/hosts)
==> vgpm: [vagrant-hostsupdater]   192.168.99.25  axs.local, keycloak  #
VAGRANT: e822a021a1afdc6c8dde3295110a3a6e (vgpm) /
9a45e779-4469-4348-9602-8273472cfd7f
==> vgpm: [vagrant-hostsupdater] Update Works
==> vgpm: Checking for guest additions in VM...
==> vgpm: [vagrant-hostsupdater] Checking for host entries
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25 vgpm.local
==> vgpm: [vagrant-hostsupdater] Writing the following entries to
(C:/WINDOWS/system32/drivers/etc/hosts)
==> vgpm: [vagrant-hostsupdater]   192.168.99.25  axs.local, keycloak  #
VAGRANT: e822a021a1afdc6c8dde3295110a3a6e (vgpm) /
9a45e779-4469-4348-9602-8273472cfd7f
==> vgpm: [vagrant-hostsupdater] Update Works
==> vgpm: [vagrant-hostsupdater] Checking for host entries
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25 vgpm.local
==> vgpm: [vagrant-hostsupdater] Writing the following entries to
(C:/WINDOWS/system32/drivers/etc/hosts)
==> vgpm: [vagrant-hostsupdater]   192.168.99.25  axs.local, keycloak  #
VAGRANT: e822a021a1afdc6c8dde3295110a3a6e (vgpm) /
9a45e779-4469-4348-9602-8273472cfd7f
==> vgpm: [vagrant-hostsupdater] Update Works
==> vgpm: [vagrant-hostsupdater] Checking for host entries
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25 vgpm.local
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25
axs.local, keycloak
==> vgpm: [vagrant-hostsupdater] Checking for host entries
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25 vgpm.local
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25
axs.local, keycloak
==> vgpm: [vagrant-hostsupdater] Checking for host entries
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25 vgpm.local
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25
axs.local, keycloak
==> vgpm: [vagrant-hostsupdater] Checking for host entries
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25 vgpm.local
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25
axs.local, keycloak
==> vgpm: [vagrant-hostsupdater] Checking for host entries
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25 vgpm.local
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25
axs.local, keycloak
==> vgpm: [vagrant-hostsupdater] Checking for host entries
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25 vgpm.local
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25
axs.local, keycloak
==> vgpm: Setting hostname...
==> vgpm: Configuring and enabling network interfaces...
==> vgpm: Rsyncing folder: /cygdrive/c/Work/GIT/axs-vgpm/ => /home/vagrant
==> vgpm:   - Exclude: [".vagrant/", ".git/"]
==> vgpm: Mounting shared folders...
    vgpm: /vagrant => C:/Work/GIT/axs-vgpm/vagrant
==> vgpm: Running provisioner: shell...
    vgpm: Running:
C:/Users/SKALIN~1/AppData/Local/Temp/vagrant-shell20201203-22712-1seb40o.sh
    ....
==> vgpm: [vagrant-hostsupdater] Checking for host entries
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25 vgpm.local
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25
axs.local, keycloak
==> vgpm: [vagrant-hostsupdater] Checking for host entries
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25 vgpm.local
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25
axs.local, keycloak
==> vgpm: [vagrant-hostsupdater] Checking for host entries
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25 vgpm.local
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25
axs.local, keycloak
==> vgpm: [vagrant-hostsupdater] Checking for host entries
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25 vgpm.local
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25
axs.local, keycloak
==> vgpm: [vagrant-hostsupdater] Checking for host entries
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25 vgpm.local
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25
axs.local, keycloak
==> vgpm: [vagrant-hostsupdater] Checking for host entries
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25 vgpm.local
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25
axs.local, keycloak
==> vgpm: [vagrant-hostsupdater] Checking for host entries
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25 vgpm.local
==> vgpm: [vagrant-hostsupdater]   found entry for: 192.168.99.25
axs.local, keycloak

**Comment by cgsmith** [comment]
@skalinkin that issue is known about. The other issues please create a new bug so we aren't resurrecting this one.
